### ISSUE TITLE
Cannot find module 'r6-discord'

### ISSUE THREAD

**Issue by Xelbak** [OGNova/r6-discord#2]
I have it installed yet it can't find the module? How do I fix this?

**Comment by OGNova** [comment]
Doesn't seem like you have it installed. Can you run `npm ls r6-discord` and then reply with a screenshot of what that outputs?

**Comment by Xelbak** [comment]
![screenshot_417](https://user-images.githubusercontent.com/42919422/45044841-dbf83700-b036-11e8-8ba0-81d12364ca0c.png)

unless running npm i r6-discord didn't actually install it then I should have it installed.

**Comment by OGNova** [comment]
Hmm, can you share the code you're using?

**Comment by Xelbak** [comment]
```const Discord = require("discord.js");
const R6Api = require('r6-discord');
const R6 = new R6Api();

exports.run = async (bot, message, args) => {

  message.delete()
  let username;
  let platform;

  if (!['uplay','xone','ps4'].includes(args[0])) return message.channel.send('**Please include the platform! example: `>r6stats [uplay | xone | ps4] <username>`**');
  if (!args[1]) return message.channel.send('**Please include the username! example: `>r6stats [uplay | xone | ps4] <username>`**');

  platform = args.shift();
  username = args.join(' ');

  R6.stats(username, platform).then(stats => {
    console.log(stats);
  }).catch(error => {
    console.log(error);
  });

}

exports.help = {
  name: "r6stats"
}
```

**Comment by OGNova** [comment]
That's really odd. I'll do some testing of my own tonight. It might just be due to NPM being broken, or it could be due to something on my part.

**Comment by OGNova** [comment]
@DopeVulcan ~~after some preliminary testing, I've found that it's not actually installing. I'll do some housekeeping for the package, and publish a new version, maybe that'll fix it.~~

Go ahead and rerun `npm i r6-discord`, for some reason, NPM wasn't installing the package due to it being published so long ago.

**Comment by Xelbak** [comment]
yes it works! now it's saying operator is not defined but I believe that would be on your end as i'm not doing anything with operators in my command just yet.

**Comment by OGNova** [comment]
It should all be working now, just let me know if you have any more issues!
